CREATE TABLE "USER_ROLE"(
        "USER_NAME"          VARCHAR2(50) NOT NULL,
        "ROLE_NAME"          VARCHAR2(50) NOT NULL,
    CONSTRAINT "USER_ROLEP1" PRIMARY KEY("USER_NAME","ROLE_NAME")
)
/
