CREATE TABLE "ZZ_JUT_PART"(
        "PART"          VARCHAR2(50) NOT NULL,
        "NOUN"          VARCHAR2(40) NOT NULL,
        "CATEGORY_INSTRUMENT"          VARCHAR2(20),
    CONSTRAINT "ZZ_JUT_PARTP1" PRIMARY KEY("PART")
)

