CREATE TABLE "ZZ_JUT_INSTRUMENT"(
        "CATEGORY_INSTRUMENT"          VARCHAR2(12) NOT NULL,
        "DESCRIPTION"          VARCHAR2(20),
        "SUPPORT_EQUIP_B"          CHAR(1),
        "CALCULATE_MTBF_B"          CHAR(1),
    CONSTRAINT "ZZ_JUT_INSTRUMENTP1" PRIMARY KEY("CATEGORY_INSTRUMENT")
)
