//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.08 at 05:57:50 PM PDT 
//


package org.jaffa.components.navigation.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *     A menu-option is used to define an option on both the 'global navigation menu' and on 
 *     the 'desktop navigation menu'. There are four options here, 
 *         
 *     component-action,
 *        	- which is a direct link to run a Jaffa Component
 *     
 *     url-action,
 *        	- which can directly run a URL. This can be a relative or absolute href, or could
 *           even be a "javascript:" based url to call client side code.
 *     
 *     sub-menu,
 *        	- which is used to describe a lower level list of menu options
 *     
 *     desktop-menu,
 *       	- which is only used in a 'global navigation menu', to infer that the
 *           these menu options are not part of the global menu, but are the root of 
 *           a desktop level menu. A definition of a desktop-menu from within a desktop
 *           menu will be treated as if it were just a 'sub-menu' definition.
 *           
 *     Note: 'label' text can be plain text, or can contain tokens [xx.yy.zz] to be derived
 *           from a resource bundle          
 *    
 * 
 * <p>Java class for menu-option complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="menu-option"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="component-action" type="{}component-action"/&gt;
 *           &lt;element name="url-action" type="{}url-action"/&gt;
 *           &lt;element name="sub-menu" type="{}sub-menu"/&gt;
 *           &lt;element name="desktop-menu" type="{}desktop-menu"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "menu-option", propOrder = {
    "label",
    "componentAction",
    "urlAction",
    "subMenu",
    "desktopMenu"
})
public class MenuOption {

    @XmlElement(required = true)
    protected String label;
    @XmlElement(name = "component-action")
    protected ComponentAction componentAction;
    @XmlElement(name = "url-action")
    protected UrlAction urlAction;
    @XmlElement(name = "sub-menu")
    protected SubMenu subMenu;
    @XmlElement(name = "desktop-menu")
    protected DesktopMenu desktopMenu;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the componentAction property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentAction }
     *     
     */
    public ComponentAction getComponentAction() {
        return componentAction;
    }

    /**
     * Sets the value of the componentAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentAction }
     *     
     */
    public void setComponentAction(ComponentAction value) {
        this.componentAction = value;
    }

    /**
     * Gets the value of the urlAction property.
     * 
     * @return
     *     possible object is
     *     {@link UrlAction }
     *     
     */
    public UrlAction getUrlAction() {
        return urlAction;
    }

    /**
     * Sets the value of the urlAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrlAction }
     *     
     */
    public void setUrlAction(UrlAction value) {
        this.urlAction = value;
    }

    /**
     * Gets the value of the subMenu property.
     * 
     * @return
     *     possible object is
     *     {@link SubMenu }
     *     
     */
    public SubMenu getSubMenu() {
        return subMenu;
    }

    /**
     * Sets the value of the subMenu property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubMenu }
     *     
     */
    public void setSubMenu(SubMenu value) {
        this.subMenu = value;
    }

    /**
     * Gets the value of the desktopMenu property.
     * 
     * @return
     *     possible object is
     *     {@link DesktopMenu }
     *     
     */
    public DesktopMenu getDesktopMenu() {
        return desktopMenu;
    }

    /**
     * Sets the value of the desktopMenu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesktopMenu }
     *     
     */
    public void setDesktopMenu(DesktopMenu value) {
        this.desktopMenu = value;
    }

}
