//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.08 at 05:57:50 PM PDT 
//


package org.jaffa.components.navigation.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jaffa.components.navigation.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jaffa.components.navigation.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubMenu }
     * 
     */
    public SubMenu createSubMenu() {
        return new SubMenu();
    }

    /**
     * Create an instance of {@link UrlAction.Url }
     * 
     */
    public UrlAction.Url createUrlActionUrl() {
        return new UrlAction.Url();
    }

    /**
     * Create an instance of {@link UrlAction }
     * 
     */
    public UrlAction createUrlAction() {
        return new UrlAction();
    }

    /**
     * Create an instance of {@link GlobalMenu }
     * 
     */
    public GlobalMenu createGlobalMenu() {
        return new GlobalMenu();
    }

    /**
     * Create an instance of {@link ComponentAction.Param }
     * 
     */
    public ComponentAction.Param createComponentActionParam() {
        return new ComponentAction.Param();
    }

    /**
     * Create an instance of {@link DesktopMenu }
     * 
     */
    public DesktopMenu createDesktopMenu() {
        return new DesktopMenu();
    }

    /**
     * Create an instance of {@link MenuOption }
     * 
     */
    public MenuOption createMenuOption() {
        return new MenuOption();
    }

    /**
     * Create an instance of {@link ComponentAction }
     * 
     */
    public ComponentAction createComponentAction() {
        return new ComponentAction();
    }

}
