SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_WS_RULES_METRICS"(
        "ID"          VARCHAR(80) NOT NULL,
        "WEB_SERVICE_NAME"          VARCHAR(300),
        "RESULT_GRAPH_RULE"          VARCHAR(4000),
        "CREATED_ON"          DATETIME,
    CONSTRAINT "J_WS_RULES_METRICSP1" PRIMARY KEY("ID")
)
GO
