//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.07 at 12:13:36 PM PST 
//


package org.jaffa.presentation.portlet.widgets.controller.usergriddomain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="grid-width" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="user-grid-column-settings" type="{}user-grid-column-settings" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gridWidth",
    "userGridColumnSettings"
})
@XmlRootElement(name = "user-grid-settings")
public class UserGridSettings {

    @XmlElement(name = "grid-width")
    protected String gridWidth;
    @XmlElement(name = "user-grid-column-settings")
    protected List<UserGridColumnSettings> userGridColumnSettings;

    /**
     * Gets the value of the gridWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridWidth() {
        return gridWidth;
    }

    /**
     * Sets the value of the gridWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridWidth(String value) {
        this.gridWidth = value;
    }

    /**
     * Gets the value of the userGridColumnSettings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userGridColumnSettings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserGridColumnSettings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserGridColumnSettings }
     * 
     * 
     */
    public List<UserGridColumnSettings> getUserGridColumnSettings() {
        if (userGridColumnSettings == null) {
            userGridColumnSettings = new ArrayList<UserGridColumnSettings>();
        }
        return this.userGridColumnSettings;
    }

}
