SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "USER_ROLE"(
        "USER_NAME"          VARCHAR(50) NOT NULL,
        "ROLE_NAME"          VARCHAR(50) NOT NULL,
    CONSTRAINT "USER_ROLEP1" PRIMARY KEY("USER_NAME","ROLE_NAME")
)
GO
