SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "USER_REQUEST"(
        "REQUEST_ID"          NUMERIC(50) IDENTITY (1, 1) NOT NULL,
        "USER_NAME"          VARCHAR(50) NOT NULL,
        "FIRST_NAME"          VARCHAR(50) NOT NULL,
        "LAST_NAME"          VARCHAR(50) NOT NULL,
        "PASSWORD"          VARCHAR(80) NOT NULL,
        "E_MAIL_ADDRESS"          VARCHAR(75),
        "SECURITY_QUESTION"          NUMERIC(20) NOT NULL,
        "SECURITY_ANSWER"          VARCHAR(50) NOT NULL,
        "REMARKS"          VARCHAR(180),
        "CREATED_DATETIME"          DATETIME,
        "PROCESSED_DATETIME"          DATETIME,
        "PROCESSED_USER"          VARCHAR(50),
        "STATUS"          VARCHAR(1),
    CONSTRAINT "USER_REQUESTP1" PRIMARY KEY("REQUEST_ID")
)
GO
