CREATE TABLE J_FORM_TEMPLATES (
        FORM_ID          BIGINT NOT NULL,
        TEMPLATE_DATA          LONGBLOB,
        LAYOUT_DATA          LONGBLOB,
    CONSTRAINT J_FORM_TEMPLATESP1 PRIMARY KEY(FORM_ID)
) TYPE=InnoDB
