CREATE TABLE J_FORM_USAGES (
        FORM_NAME          VARCHAR(20) NOT NULL,
        EVENT_NAME          VARCHAR(20) NOT NULL,
        FORM_ALTERNATE          VARCHAR(20),
        COPIES          INT,
        CREATED_ON          DATETIME,
        CREATED_BY          VARCHAR(20),
        LAST_CHANGED_ON          DATETIME,
        LAST_CHANGED_BY          VARCHAR(20),
    CONSTRAINT J_FORM_USAGESP1 PRIMARY KEY(FORM_NAME,EVENT_NAME)
) TYPE=InnoDB
