CREATE TABLE J_OUTPUT_TYPES (
        OUTPUT_TYPE          VARCHAR(20) NOT NULL,
        DESCRIPTION          VARCHAR(100),
        DIRECT_PRINTING          CHAR(1) NOT NULL,
        CREATED_ON          DATETIME,
        CREATED_BY          VARCHAR(20),
        LAST_CHANGED_ON          DATETIME,
        LAST_CHANGED_BY          VARCHAR(20),
    CONSTRAINT J_OUTPUT_TYPESP1 PRIMARY KEY(OUTPUT_TYPE)
) TYPE=InnoDB
