CREATE TABLE J_OUTPUT_COMMANDS (
        OUTPUT_COMMAND_ID          BIGINT NOT NULL AUTO_INCREMENT,
        OUTPUT_TYPE          VARCHAR(20) NOT NULL,
        SEQUENCE_NO          BIGINT NOT NULL,
        OS_PATTERN          VARCHAR(255) NOT NULL,
        COMMAND_LINE          VARCHAR(255) NOT NULL,
        CREATED_ON          DATETIME,
        CREATED_BY          VARCHAR(20),
        LAST_CHANGED_ON          DATETIME,
        LAST_CHANGED_BY          VARCHAR(20),
    CONSTRAINT J_OUTPUT_COMMANDSP1 PRIMARY KEY(OUTPUT_COMMAND_ID)
) TYPE=InnoDB
