CREATE TABLE "J_WS_RULES_METRICS"(
        "ID"          VARCHAR2(80) NOT NULL,
        "WEB_SERVICE_NAME"          VARCHAR2(300),
        "RESULT_GRAPH_RULE"          VARCHAR2(4000),
        "CREATED_ON"          DATE,
    CONSTRAINT "J_WS_RULES_METRICSP1" PRIMARY KEY("ID")
)
/
