SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_SOA_EVENTS"(
        "EVENT_ID"          VARCHAR(80) NOT NULL,
        "EVENT_NAME"          VARCHAR(100) NOT NULL,
        "DESCRIPTION"          VARCHAR(100),
        "CREATED_ON"          DATETIME,
        "CREATED_BY"          VARCHAR(20),
        "LOCAL_ID"          VARCHAR(80),        
    CONSTRAINT "J_SOA_EVENTSP1" PRIMARY KEY("EVENT_ID")
)
GO
