SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_TRANSACTION_DEPENDENCIES"(
        "TRANSACTION_ID"          VARCHAR(80) NOT NULL,
        "DEPENDS_ON_ID"          VARCHAR(80) NOT NULL,
        "STATUS"          VARCHAR(20),
    CONSTRAINT "J_TRANSACTION_DEPENDENCIESP1" PRIMARY KEY("TRANSACTION_ID","DEPENDS_ON_ID")
)
GO
