SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_TRANSACTION_PAYLOADS"(
        "ID"          VARCHAR(80) NOT NULL,
        "EXTERNAL_MESSAGE"          IMAGE,
        "INTERNAL_MESSAGE"          IMAGE,
        "INTERNAL_MESSAGE_CLASS"          VARCHAR(2000),
    CONSTRAINT "J_TRANSACTION_PAYLOADSP1" PRIMARY KEY("ID")
)
GO
