CREATE TABLE "J_AUDIT_TRANSACTIONS"(
        "TRANSACTION_ID"          VARCHAR2(80) NOT NULL,
        "PROCESS_NAME"          VARCHAR2(80),
        "SUB_PROCESS_NAME"          VARCHAR2(80),
        "REASON"          VARCHAR2(250),
        "CREATED_BY"          VARCHAR2(20),
        "CREATED_ON"          DATE,
    CONSTRAINT "J_AUDIT_TRANSACTIONSP1" PRIMARY KEY("TRANSACTION_ID")
)
/
