CREATE TABLE "ZZ_JUT_PART_REM_PIC"(
        "PART"          VARCHAR(50) NOT NULL,
        "REMARKS"          VARCHAR(MAX),
        "PICTURE"          VARBINARY(MAX),
    CONSTRAINT "ZZ_JUT_PART_REM_PICP1" PRIMARY KEY("PART")
)
