CREATE TABLE "ZZ_JUT_VALID_FIELD_VALUE"(
"TABLE_NAME" VARCHAR(20),
"FIELD_NAME" VARCHAR(30),
"LEGAL_VALUE" VARCHAR(20),
"DESCRIPTION" VARCHAR(40),
"REMARKS" VARCHAR(250),
CONSTRAINT "ZZ_JUT_VALID_FIELD_VALUEP1" PRIMARY KEY(
"TABLE_NAME","FIELD_NAME","LEGAL_VALUE"))