CREATE TABLE "ZZ_JUT_INSTRUMENT"(
        "CATEGORY_INSTRUMENT"          VARCHAR(12) NOT NULL,
        "DESCRIPTION"          VARCHAR(20),
        "SUPPORT_EQUIP_B"          BIT,
        "CALCULATE_MTBF_B"          CHAR(1),
    CONSTRAINT "ZZ_JUT_INSTRUMENTP1" PRIMARY KEY("CATEGORY_INSTRUMENT")
)
