CREATE TABLE "ZZ_JUT_PART"(
        "PART"          VARCHAR(50) NOT NULL,
        "NOUN"          VARCHAR(40) NOT NULL,
        "CATEGORY_INSTRUMENT"          VARCHAR(20),
    CONSTRAINT "ZZ_JUT_PARTP1" PRIMARY KEY("PART")
)
