SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_FORM_EVENTS"(
        "EVENT_NAME"          VARCHAR(20) NOT NULL,
        "DESCRIPTION"          VARCHAR(100),
        "CREATED_ON"          DATETIME,
        "CREATED_BY"          VARCHAR(20),
        "LAST_CHANGED_ON"          DATETIME,
        "LAST_CHANGED_BY"          VARCHAR(20),
    CONSTRAINT "J_FORM_EVENTSP1" PRIMARY KEY("EVENT_NAME")
)
GO
