SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_FORM_TEMPLATES"(
        "FORM_ID"          NUMERIC(20) NOT NULL,
        "TEMPLATE_DATA"          IMAGE,
        "LAYOUT_DATA"          IMAGE,
    CONSTRAINT "J_FORM_TEMPLATESP1" PRIMARY KEY("FORM_ID")
)
GO
