SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_OUTPUT_COMMANDS"(
        "OUTPUT_COMMAND_ID"          NUMERIC(10) IDENTITY (1, 1) NOT NULL,
        "OUTPUT_TYPE"          VARCHAR(20) NOT NULL,
        "SEQUENCE_NO"          NUMERIC(10) NOT NULL,
        "OS_PATTERN"          VARCHAR(255) NOT NULL,
        "COMMAND_LINE"          VARCHAR(255) NOT NULL,
        "CREATED_ON"          DATETIME,
        "CREATED_BY"          VARCHAR(20),
        "LAST_CHANGED_ON"          DATETIME,
        "LAST_CHANGED_BY"          VARCHAR(20),
    CONSTRAINT "J_OUTPUT_COMMANDSP1" PRIMARY KEY("OUTPUT_COMMAND_ID")
)
GO
