DROP TABLE ZZ_QRTZ_CALENDARS;
CREATE TABLE ZZ_QRTZ_CALENDARS AS SELECT * FROM QRTZ_CALENDARS;

DROP TABLE ZZ_QRTZ_FIRED_TRIGGERS;
CREATE TABLE ZZ_QRTZ_FIRED_TRIGGERS AS SELECT * FROM QRTZ_FIRED_TRIGGERS;

DROP TABLE ZZ_QRTZ_TRIGGER_LISTENERS;
CREATE TABLE ZZ_QRTZ_TRIGGER_LISTENERS AS SELECT * FROM QRTZ_TRIGGER_LISTENERS;

DROP TABLE ZZ_QRTZ_BLOB_TRIGGERS;
CREATE TABLE ZZ_QRTZ_BLOB_TRIGGERS AS SELECT * FROM QRTZ_BLOB_TRIGGERS;

DROP TABLE ZZ_QRTZ_CRON_TRIGGERS;
CREATE TABLE ZZ_QRTZ_CRON_TRIGGERS AS SELECT * FROM QRTZ_CRON_TRIGGERS;

DROP TABLE ZZ_QRTZ_SIMPLE_TRIGGERS;
CREATE TABLE ZZ_QRTZ_SIMPLE_TRIGGERS AS SELECT * FROM QRTZ_SIMPLE_TRIGGERS;

DROP TABLE ZZ_QRTZ_TRIGGERS;
CREATE TABLE ZZ_QRTZ_TRIGGERS AS SELECT * FROM QRTZ_TRIGGERS;

DROP TABLE ZZ_QRTZ_JOB_LISTENERS;
CREATE TABLE ZZ_QRTZ_JOB_LISTENERS AS SELECT * FROM QRTZ_JOB_LISTENERS;

DROP TABLE ZZ_QRTZ_JOB_DETAILS;
CREATE TABLE ZZ_QRTZ_JOB_DETAILS AS SELECT * FROM QRTZ_JOB_DETAILS;

DROP TABLE ZZ_QRTZ_PAUSED_TRIGGER_GRPS;
CREATE TABLE ZZ_QRTZ_PAUSED_TRIGGER_GRPS AS SELECT * FROM QRTZ_PAUSED_TRIGGER_GRPS;

DROP TABLE ZZ_QRTZ_SCHEDULER_STATE;
CREATE TABLE ZZ_QRTZ_SCHEDULER_STATE AS SELECT * FROM QRTZ_SCHEDULER_STATE;
