//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 09:47:29 AM PST 
//


package org.jaffa.dwr.services.configdomain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for allow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="allow">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element ref="{}create" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}convert" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}filter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "allow", propOrder = {
    "createOrConvertOrFilter"
})
public class Allow {

    @XmlElements({
        @XmlElement(name = "create", type = Create.class),
        @XmlElement(name = "convert", type = Convert.class),
        @XmlElement(name = "filter", type = Filter.class)
    })
    protected List<Object> createOrConvertOrFilter;

    /**
     * Gets the value of the createOrConvertOrFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the createOrConvertOrFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreateOrConvertOrFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Create }
     * {@link Convert }
     * {@link Filter }
     * 
     * 
     */
    public List<Object> getCreateOrConvertOrFilter() {
        if (createOrConvertOrFilter == null) {
            createOrConvertOrFilter = new ArrayList<Object>();
        }
        return this.createOrConvertOrFilter;
    }

}
