//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 09:47:29 AM PST 
//


package org.jaffa.dwr.services.configdomain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for create complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="create">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element ref="{}param" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}exclude" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}auth" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}filter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="creator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="javascript" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scope">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="application"/>
 *             &lt;enumeration value="session"/>
 *             &lt;enumeration value="script"/>
 *             &lt;enumeration value="request"/>
 *             &lt;enumeration value="page"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "create", propOrder = {
    "paramOrIncludeOrExclude"
})
public class Create {

    @XmlElements({
        @XmlElement(name = "include", type = Include.class),
        @XmlElement(name = "filter", type = Filter.class),
        @XmlElement(name = "param", type = Param.class),
        @XmlElement(name = "auth", type = Auth.class),
        @XmlElement(name = "exclude", type = Exclude.class)
    })
    protected List<Object> paramOrIncludeOrExclude;
    @XmlAttribute
    protected String creator;
    @XmlAttribute
    protected String javascript;
    @XmlAttribute
    protected String scope;

    /**
     * Gets the value of the paramOrIncludeOrExclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paramOrIncludeOrExclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParamOrIncludeOrExclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Include }
     * {@link Filter }
     * {@link Param }
     * {@link Auth }
     * {@link Exclude }
     * 
     * 
     */
    public List<Object> getParamOrIncludeOrExclude() {
        if (paramOrIncludeOrExclude == null) {
            paramOrIncludeOrExclude = new ArrayList<Object>();
        }
        return this.paramOrIncludeOrExclude;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the javascript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavascript() {
        return javascript;
    }

    /**
     * Sets the value of the javascript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavascript(String value) {
        this.javascript = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

}
