//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 04:51:25 PM PST 
//


package org.jaffa.transaction.services.configdomain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for loggingName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="loggingName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CorrelationType"/>
 *     &lt;enumeration value="CorrelationKey1"/>
 *     &lt;enumeration value="CorrelationKey2"/>
 *     &lt;enumeration value="CorrelationKey3"/>
 *     &lt;enumeration value="ProcessName"/>
 *     &lt;enumeration value="SubProcessName"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "loggingName")
@XmlEnum
public enum LoggingName {

    @XmlEnumValue("CorrelationType")
    CORRELATION_TYPE("CorrelationType"),
    @XmlEnumValue("CorrelationKey1")
    CORRELATION_KEY_1("CorrelationKey1"),
    @XmlEnumValue("CorrelationKey2")
    CORRELATION_KEY_2("CorrelationKey2"),
    @XmlEnumValue("CorrelationKey3")
    CORRELATION_KEY_3("CorrelationKey3"),
    @XmlEnumValue("ProcessName")
    PROCESS_NAME("ProcessName"),
    @XmlEnumValue("SubProcessName")
    SUB_PROCESS_NAME("SubProcessName");
    private final String value;

    LoggingName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LoggingName fromValue(String v) {
        for (LoggingName c: LoggingName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
