//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 04:51:25 PM PST 
//


package org.jaffa.transaction.services.configdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Controls access to viewing and maintaining Transactions of a certain Type
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;&lt;b&gt;browse&lt;/b&gt;: contains the business-function for controlling access
 *             &lt;ul&gt;&lt;li&gt;&lt;b&gt;attribute absent&lt;/b&gt;: All users have access to Transactions of a certain Type&lt;/li&gt;&lt;li&gt;&lt;b&gt;attribute empty&lt;/b&gt;: No user will have access to Transactions of a certain Type&lt;/li&gt;
 *             &lt;/ul&gt;
 *           &lt;/li&gt;&lt;li&gt;&lt;b&gt;admin&lt;/b&gt;: contains the business-function for controlling access to the delete and resubmit actions on the accessible Transactions of a certain Type
 *             &lt;ul&gt;&lt;li&gt;&lt;b&gt;attribute absent&lt;/b&gt;: All users can Delete and Resubmit&lt;/li&gt;&lt;li&gt;&lt;b&gt;attribute empty&lt;/b&gt;: No user can Delete and Resubmit&lt;/li&gt;
 *             &lt;/ul&gt;
 *           &lt;/li&gt;
 *         &lt;/ul&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for security complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="security">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="browse" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="admin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "security")
public class Security {

    @XmlAttribute
    protected String browse;
    @XmlAttribute
    protected String admin;

    /**
     * Gets the value of the browse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrowse() {
        return browse;
    }

    /**
     * Sets the value of the browse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrowse(String value) {
        this.browse = value;
    }

    /**
     * Gets the value of the admin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * Sets the value of the admin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmin(String value) {
        this.admin = value;
    }

}
