//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 04:51:25 PM PST 
//


package org.jaffa.transaction.services.configdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Maps a POJO to a Transaction Type, and declares the Transaction handler
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;&lt;b&gt;lock-check&lt;/b&gt;: lists the elements to check in the Headers of existing Transactions, the presence of which would result in a LockingServiceException. The check is performed before writing the Transaction.&lt;/li&gt;&lt;li&gt;&lt;b&gt;header&lt;/b&gt;: lists the elements to add to the Transaction header&lt;/li&gt;&lt;li&gt;&lt;b&gt;dataBean&lt;/b&gt;: the fully qualified class name of the POJO&lt;/li&gt;&lt;li&gt;&lt;b&gt;type&lt;/b&gt;: the Transaction Type&lt;/li&gt;&lt;li&gt;&lt;b&gt;subType&lt;/b&gt;: the Transaction subType&lt;/li&gt;&lt;li&gt;&lt;b&gt;toClass&lt;/b&gt;: the fully qualified class name of the handler. This attribute need not be specified for an Outbound Transaction&lt;/li&gt;&lt;li&gt;&lt;b&gt;toMethod&lt;/b&gt;: the handler method, which gets invoked by the TransactionConsumer, which consumes the Transaction. The method signature should have the POJO as an input argument.&lt;/li&gt;&lt;li&gt;&lt;b&gt;description&lt;/b&gt;: the description&lt;/li&gt;
 *         &lt;/ul&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for transactionInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transactionInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lock-check" type="{}lock-check" minOccurs="0"/>
 *         &lt;element name="header" type="{}header" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dataBean" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="toClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="toMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transactionInfo", propOrder = {
    "lockCheck",
    "header"
})
public class TransactionInfo {

    @XmlElement(name = "lock-check")
    protected LockCheck lockCheck;
    protected Header header;
    @XmlAttribute(required = true)
    protected String dataBean;
    @XmlAttribute(required = true)
    protected String type;
    @XmlAttribute
    protected String subType;
    @XmlAttribute
    protected String toClass;
    @XmlAttribute
    protected String toMethod;
    @XmlAttribute
    protected String description;

    /**
     * Gets the value of the lockCheck property.
     * 
     * @return
     *     possible object is
     *     {@link LockCheck }
     *     
     */
    public LockCheck getLockCheck() {
        return lockCheck;
    }

    /**
     * Sets the value of the lockCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link LockCheck }
     *     
     */
    public void setLockCheck(LockCheck value) {
        this.lockCheck = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the dataBean property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataBean() {
        return dataBean;
    }

    /**
     * Sets the value of the dataBean property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataBean(String value) {
        this.dataBean = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubType(String value) {
        this.subType = value;
    }

    /**
     * Gets the value of the toClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToClass() {
        return toClass;
    }

    /**
     * Sets the value of the toClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToClass(String value) {
        this.toClass = value;
    }

    /**
     * Gets the value of the toMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToMethod() {
        return toMethod;
    }

    /**
     * Sets the value of the toMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToMethod(String value) {
        this.toMethod = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
