//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 04:51:25 PM PST 
//


package org.jaffa.transaction.services.configdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Provides additional information for a Transaction Type
 * <p/>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;&lt;b&gt;display-param&lt;/b&gt;: lists the header elements to display when viewing Transactions of this Type&lt;/li&gt;&lt;li&gt;&lt;b&gt;security&lt;/b&gt;: controls access to viewing and maintaining Transactions of this Type&lt;/li&gt;&lt;li&gt;&lt;b&gt;name&lt;/b&gt;: the name of this Transaction Type&lt;/li&gt;&lt;li&gt;&lt;b&gt;description&lt;/b&gt;: the description&lt;/li&gt;&lt;li&gt;&lt;b&gt;queueName&lt;/b&gt;: the name of the JMS queue to which Transactions of this type will be written&lt;/li&gt;&lt;li&gt;&lt;b&gt;label&lt;/b&gt;: the the label to be shown on the UI&lt;/li&gt;
 *         &lt;/ul&gt;
 * </pre>
 * <p/>
 * <p/>
 * <p/>
 * <p>Java class for typeInfo complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="typeInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="display-param" type="{}display-param" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="security" type="{}security" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="queueName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeInfo", propOrder = {
        "displayParam",
        "security"
})
public class TypeInfo {

    @XmlElement(name = "display-param")
    protected List<DisplayParam> displayParam;
    protected Security security;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String description;
    @XmlAttribute(required = true)
    protected String queueName;
    @XmlAttribute
    protected Boolean singleton;
    @XmlAttribute(required = true)
    protected String label;

    /**
     * Gets the value of the displayParam property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayParam property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayParam().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayParam }
     */
    public List<DisplayParam> getDisplayParam() {
        if (displayParam == null) {
            displayParam = new ArrayList<DisplayParam>();
        }
        return this.displayParam;
    }

    /**
     * Gets the value of the security property.
     *
     * @return possible object is
     *         {@link Security }
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     *
     * @param value allowed object is
     *              {@link Security }
     */
    public void setSecurity(Security value) {
        this.security = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the queueName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getQueueName() {
        return queueName;
    }

    /**
     * Sets the value of the queueName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQueueName(String value) {
        this.queueName = value;
    }

    /**
     * Gets the value of the singleton property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean getSingleton() {
        return singleton;
    }

    /**
     * Sets the value of the singleton property.
     *
     * @param singleton allowed object is
     *                  {@link boolean }
     */
    public void setSingleton(Boolean singleton) {
        this.singleton = singleton;
    }

    /**
     * Gets the value of the label property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLabel(String value) {
        this.label = value;
    }
}