DECLARE
  v_count NUMBER;

BEGIN

  SELECT Count(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'J_BUSINESS_EVENT_LOGSI2';
  IF (v_count = 0) THEN
     EXECUTE IMMEDIATE 'CREATE INDEX J_BUSINESS_EVENT_LOGSI2 ON J_BUSINESS_EVENT_LOGS  (SCHEDULED_TASK_ID)'  ;
  END IF;

END;
/