DECLARE
  v_count NUMBER;

BEGIN  

  SELECT Count(*) INTO v_count FROM USER_INDEXES 
    WHERE INDEX_NAME = 'J_BUSINESS_EVENT_LOGSI5';
  IF (v_count = 0) THEN
     EXECUTE IMMEDIATE 'CREATE INDEX J_BUSINESS_EVENT_LOGSI5 ON J_BUSINESS_EVENT_LOGS (CORRELATION_TYPE)'  ;
  END IF;  

END;
/
