SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_VALID_FIELD_VALUES"(
        "TABLE_NAME"          VARCHAR(20) NOT NULL,
        "FIELD_NAME"          VARCHAR(30) NOT NULL,
        "LEGAL_VALUE"          VARCHAR(20) NOT NULL,
        "DESCRIPTION"          VARCHAR(40),
        "REMARKS"          VARCHAR(250),
    CONSTRAINT "J_VALID_FIELD_VALUESP1" PRIMARY KEY("TABLE_NAME","FIELD_NAME","LEGAL_VALUE")
)
GO
