CREATE TABLE "J_FORM_TEMPLATES"(
        "FORM_ID"          NUMBER(20) NOT NULL,
        "TEMPLATE_DATA"          BLOB,
        "LAYOUT_DATA"          BLOB,
    CONSTRAINT "J_FORM_TEMPLATESP1" PRIMARY KEY("FORM_ID")
)
/
