-- Upgrading Quartz tables as per the changes from version 1.5.2 to 1.6.2

ALTER TABLE QRTZ_CALENDARS MODIFY(CALENDAR_NAME VARCHAR2(200));

ALTER TABLE QRTZ_FIRED_TRIGGERS ADD(PRIORITY NUMBER(13));
UPDATE QRTZ_FIRED_TRIGGERS SET PRIORITY=5 WHERE PRIORITY IS NULL;
ALTER TABLE QRTZ_FIRED_TRIGGERS MODIFY(PRIORITY NUMBER(13) NOT NULL);
ALTER TABLE QRTZ_FIRED_TRIGGERS MODIFY(TRIGGER_NAME VARCHAR2(200), TRIGGER_GROUP VARCHAR2(200), INSTANCE_NAME VARCHAR2(200), JOB_NAME VARCHAR2(200), JOB_GROUP VARCHAR2(200));

ALTER TABLE QRTZ_TRIGGER_LISTENERS MODIFY(TRIGGER_NAME  VARCHAR2(200), TRIGGER_GROUP VARCHAR2(200), TRIGGER_LISTENER VARCHAR2(200));

ALTER TABLE QRTZ_BLOB_TRIGGERS MODIFY(TRIGGER_NAME VARCHAR2(200), TRIGGER_GROUP VARCHAR2(200));

ALTER TABLE QRTZ_CRON_TRIGGERS MODIFY(TRIGGER_NAME VARCHAR2(200), TRIGGER_GROUP VARCHAR2(200), CRON_EXPRESSION VARCHAR2(120));

ALTER TABLE QRTZ_SIMPLE_TRIGGERS MODIFY(TRIGGER_NAME VARCHAR2(200), TRIGGER_GROUP VARCHAR2(200));

ALTER TABLE QRTZ_TRIGGERS ADD(PRIORITY NUMBER(13) NULL);
UPDATE QRTZ_TRIGGERS SET PRIORITY=5 WHERE PRIORITY IS NULL;
ALTER TABLE QRTZ_TRIGGERS MODIFY(TRIGGER_NAME VARCHAR2(200), TRIGGER_GROUP VARCHAR2(200), JOB_NAME  VARCHAR2(200), JOB_GROUP VARCHAR2(200), DESCRIPTION VARCHAR2(250), CALENDAR_NAME VARCHAR2(200));

ALTER TABLE QRTZ_JOB_LISTENERS MODIFY(JOB_NAME  VARCHAR2(200), JOB_GROUP VARCHAR2(200), JOB_LISTENER VARCHAR2(200));

ALTER TABLE QRTZ_JOB_DETAILS MODIFY(JOB_NAME  VARCHAR2(200), JOB_GROUP VARCHAR2(200), DESCRIPTION VARCHAR2(250), JOB_CLASS_NAME   VARCHAR2(250));

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS MODIFY(TRIGGER_GROUP  VARCHAR2(200));

ALTER TABLE QRTZ_SCHEDULER_STATE DROP(RECOVERER);
ALTER TABLE QRTZ_SCHEDULER_STATE MODIFY(INSTANCE_NAME VARCHAR2(200));
