CREATE TABLE "J_VALID_FIELD_VALUES"(
        "TABLE_NAME"          VARCHAR2(20) NOT NULL,
        "FIELD_NAME"          VARCHAR2(30) NOT NULL,
        "LEGAL_VALUE"          VARCHAR2(20) NOT NULL,
        "DESCRIPTION"          VARCHAR2(40),
        "REMARKS"          VARCHAR2(250),
    CONSTRAINT "J_VALID_FIELD_VALUESP1" PRIMARY KEY("TABLE_NAME","FIELD_NAME","LEGAL_VALUE")
)
/
