//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.07 at 12:13:37 PM PST 
//


package org.jaffa.persistence.engines.jdbcengine.configservice.initdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for database complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="database">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connection-factory" type="{}connection-factory"/>
 *         &lt;element name="hitlistSize" type="{}hitlistSize"/>
 *         &lt;element name="jdbcSecurityPlugin" type="{}jdbcSecurityPlugin" minOccurs="0"/>
 *         &lt;element name="usePreparedStatement" type="{}usePreparedStatement" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="engine" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "database", propOrder = {
    "connectionFactory",
    "hitlistSize",
    "jdbcSecurityPlugin",
    "usePreparedStatement"
})
public class Database {

    @XmlElement(name = "connection-factory", required = true)
    protected ConnectionFactory connectionFactory;
    @XmlElement(required = true)
    protected HitlistSize hitlistSize;
    protected JdbcSecurityPlugin jdbcSecurityPlugin;
    protected UsePreparedStatement usePreparedStatement;
    @XmlAttribute(required = true)
    protected String engine;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the connectionFactory property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionFactory }
     *     
     */
    public ConnectionFactory getConnectionFactory() {
        return connectionFactory;
    }

    /**
     * Sets the value of the connectionFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionFactory }
     *     
     */
    public void setConnectionFactory(ConnectionFactory value) {
        this.connectionFactory = value;
    }

    /**
     * Gets the value of the hitlistSize property.
     * 
     * @return
     *     possible object is
     *     {@link HitlistSize }
     *     
     */
    public HitlistSize getHitlistSize() {
        return hitlistSize;
    }

    /**
     * Sets the value of the hitlistSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitlistSize }
     *     
     */
    public void setHitlistSize(HitlistSize value) {
        this.hitlistSize = value;
    }

    /**
     * Gets the value of the jdbcSecurityPlugin property.
     * 
     * @return
     *     possible object is
     *     {@link JdbcSecurityPlugin }
     *     
     */
    public JdbcSecurityPlugin getJdbcSecurityPlugin() {
        return jdbcSecurityPlugin;
    }

    /**
     * Sets the value of the jdbcSecurityPlugin property.
     * 
     * @param value
     *     allowed object is
     *     {@link JdbcSecurityPlugin }
     *     
     */
    public void setJdbcSecurityPlugin(JdbcSecurityPlugin value) {
        this.jdbcSecurityPlugin = value;
    }

    /**
     * Gets the value of the usePreparedStatement property.
     * 
     * @return
     *     possible object is
     *     {@link UsePreparedStatement }
     *     
     */
    public UsePreparedStatement getUsePreparedStatement() {
        return usePreparedStatement;
    }

    /**
     * Sets the value of the usePreparedStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsePreparedStatement }
     *     
     */
    public void setUsePreparedStatement(UsePreparedStatement value) {
        this.usePreparedStatement = value;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngine(String value) {
        this.engine = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
