//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.07 at 12:13:37 PM PST 
//


package org.jaffa.persistence.engines.jdbcengine.configservice.initdomain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="database" type="{}database" maxOccurs="unbounded"/>
 *         &lt;element name="preload" type="{}preload" minOccurs="0"/>
 *         &lt;element name="conf-location" type="{}conf-location"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "database",
    "preload",
    "confLocation"
})
@XmlRootElement(name = "init")
public class Init {

    @XmlElement(required = true)
    protected List<Database> database;
    protected Preload preload;
    @XmlElement(name = "conf-location", required = true)
    protected ConfLocation confLocation;

    /**
     * Gets the value of the database property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the database property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatabase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Database }
     * 
     * 
     */
    public List<Database> getDatabase() {
        if (database == null) {
            database = new ArrayList<Database>();
        }
        return this.database;
    }

    /**
     * Gets the value of the preload property.
     * 
     * @return
     *     possible object is
     *     {@link Preload }
     *     
     */
    public Preload getPreload() {
        return preload;
    }

    /**
     * Sets the value of the preload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Preload }
     *     
     */
    public void setPreload(Preload value) {
        this.preload = value;
    }

    /**
     * Gets the value of the confLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ConfLocation }
     *     
     */
    public ConfLocation getConfLocation() {
        return confLocation;
    }

    /**
     * Sets the value of the confLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfLocation }
     *     
     */
    public void setConfLocation(ConfLocation value) {
        this.confLocation = value;
    }

}
