//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.07 at 12:13:37 PM PST 
//


package org.jaffa.persistence.engines.jdbcengine.configservice.initdomain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jaffa.persistence.engines.jdbcengine.configservice.initdomain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jaffa.persistence.engines.jdbcengine.configservice.initdomain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Init }
     * 
     */
    public Init createInit() {
        return new Init();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link UsePreparedStatement }
     * 
     */
    public UsePreparedStatement createUsePreparedStatement() {
        return new UsePreparedStatement();
    }

    /**
     * Create an instance of {@link HitlistSize }
     * 
     */
    public HitlistSize createHitlistSize() {
        return new HitlistSize();
    }

    /**
     * Create an instance of {@link ConnectionFactory }
     * 
     */
    public ConnectionFactory createConnectionFactory() {
        return new ConnectionFactory();
    }

    /**
     * Create an instance of {@link Preload }
     * 
     */
    public Preload createPreload() {
        return new Preload();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link DirLoc }
     * 
     */
    public DirLoc createDirLoc() {
        return new DirLoc();
    }

    /**
     * Create an instance of {@link ConfLocation }
     * 
     */
    public ConfLocation createConfLocation() {
        return new ConfLocation();
    }

    /**
     * Create an instance of {@link PreloadClass }
     * 
     */
    public PreloadClass createPreloadClass() {
        return new PreloadClass();
    }

    /**
     * Create an instance of {@link JdbcSecurityPlugin }
     * 
     */
    public JdbcSecurityPlugin createJdbcSecurityPlugin() {
        return new JdbcSecurityPlugin();
    }

}
