CREATE TABLE J_FLEX_FIELDS_DEL (
        FLEX_FIELD_ID          VARCHAR(80) NOT NULL,
        OBJECT_NAME          VARCHAR(80) NOT NULL,
        KEY1          VARCHAR(80) NOT NULL,
        VERSION_NUMBER          BIGINT,
        DELETION_CREATED_ON          DATETIME
) ENGINE=InnoDB
