CREATE TABLE ACTIVITYCODE (
        ACTIVITY_CODE          VARCHAR(50) NOT NULL,
        PROJECT_CODE          VARCHAR(50) NOT NULL,
        DESCRIPTION          VARCHAR(50) NOT NULL,
    CONSTRAINT ACTIVITYCODEP1 PRIMARY KEY(ACTIVITY_CODE)
) TYPE=InnoDB
