CREATE TABLE TASKCODE (
        TASK_CODE          VARCHAR(50) NOT NULL,
        ACTIVITY_CODE          VARCHAR(50) NOT NULL,
        DESCRIPTION          VARCHAR(50) NOT NULL,
    CONSTRAINT TASKCODEP1 PRIMARY KEY(TASK_CODE)
) TYPE=InnoDB
