CREATE TABLE USERTIMEENTRY (
        USER_NAME          VARCHAR(50) NOT NULL,
        PROJECT_CODE          VARCHAR(50) NOT NULL,
        ACTIVITY_CODE          VARCHAR(50) NOT NULL,
        TASK_CODE          VARCHAR(50) NOT NULL,
        PERIOD_START          DATETIME NOT NULL,
        PERIOD_END          DATETIME NOT NULL,
    CONSTRAINT USERTIMEENTRYP1 PRIMARY KEY(USER_NAME,PROJECT_CODE,TASK_CODE,PERIOD_START,PERIOD_END)
) TYPE=InnoDB
