CREATE TABLE J_TRANSACTION_FIELDS (
        TRANSACTION_ID          VARCHAR(80) NOT NULL,
        FIELD_NAME          VARCHAR(80) NOT NULL,
        VALUE          TEXT,
    CONSTRAINT J_TRANSACTION_FIELDSP1 PRIMARY KEY(TRANSACTION_ID,FIELD_NAME)
) TYPE=InnoDB
