--DMR BUG 34065 - Create new index on J_ATTACHMENTS


DECLARE
  v_count NUMBER;

BEGIN  

  SELECT Count(*) INTO v_count FROM USER_INDEXES 
    WHERE INDEX_NAME = 'J_ATTACHMENTSI2';
  IF (v_count = 0) THEN
     EXECUTE IMMEDIATE 'CREATE INDEX J_ATTACHMENTSI2 ON J_ATTACHMENTS (SERIALIZED_KEY)'  ;
  END IF;  

END;
/




