//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.07 at 03:53:59 PM PST 
//


package org.jaffa.modules.scheduler.services.configdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "task")
public class Task {

    @XmlAttribute
    protected Boolean autoCreateDataBean;
    @XmlAttribute(required = true)
    protected String dataBean;
    @XmlAttribute(required = true)
    protected String type;

    /**
     * Gets the value of the autoCreateDataBean property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isAutoCreateDataBean() {
        if (autoCreateDataBean == null) {
            return true;
        } else {
            return autoCreateDataBean;
        }
    }

    /**
     * Sets the value of the autoCreateDataBean property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setAutoCreateDataBean(Boolean value) {
        this.autoCreateDataBean = value;
    }

    /**
     * Gets the value of the dataBean property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDataBean() {
        return dataBean;
    }

    /**
     * Sets the value of the dataBean property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDataBean(String value) {
        this.dataBean = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }
}
