CREATE TABLE ZZ_JUT_PART_PIC (
        PART          VARCHAR(50) NOT NULL,
        SMALL_PICTURE          LONGBLOB,
        PICTURE          LONGBLOB,
    CONSTRAINT ZZ_JUT_PART_PICP1 PRIMARY KEY(PART)
) TYPE=InnoDB
