CREATE TABLE ZZ_JUT_PART_ADDITIONAL (
        PART            CHAR(50) NOT NULL,
        FIELD1          CHAR(20) NOT NULL,
        FIELD2          CHAR(20),
        FIELD3          CHAR(20),
    CONSTRAINT ZZ_JUT_PART_ADDITIONALP1 PRIMARY KEY(PART)
) TYPE=InnoDB
