CREATE TABLE ZZ_JUT_VALID_FIELD_VALUE (
TABLE_NAME VARCHAR(20) NOT NULL,
FIELD_NAME VARCHAR(30) NOT NULL,
LEGAL_VALUE VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(40),
REMARKS VARCHAR(250),
PRIMARY KEY (TABLE_NAME,FIELD_NAME,LEGAL_VALUE)) TYPE=InnoDB