CREATE TABLE J_ATTACHMENTS_DEL (
        ATTACHMENT_ID          VARCHAR(80) NOT NULL,
        SERIALIZED_KEY          TEXT NOT NULL,
        VERSION_NUMBER          BIGINT,
        DELETION_CREATED_ON          DATETIME
) ENGINE=InnoDB
