CREATE TABLE J_AUDIT_TRANSACTION_OVERFLOW (
        FIELD_ID          VARCHAR(80) NOT NULL,
        OBJECT_ID          VARCHAR(80) NOT NULL,
        FIELD_NAME          VARCHAR(80) NOT NULL,
        FROM_VALUE          LONGTEXT,
        TO_VALUE          LONGTEXT
) ENGINE=InnoDB
