//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 05:28:27 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mirotechnologies.com/GOLDesp/JMS/OutboundEvents", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jaffa.soa.services.event;
