//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 04:28:25 PM PDT 
//


package org.jaffa.modules.messaging.services.configdomain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="message" type="{}messageInfo"/&gt;
 *           &lt;element name="queue" type="{}queueInfo"/&gt;
 *           &lt;element name="topic" type="{}topicInfo"/&gt;
 *           &lt;element name="message-filter" type="{}message-filter"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageOrQueueOrTopic"
})
@XmlRootElement(name = "config")
public class Config {

    @XmlElements({
        @XmlElement(name = "queue", type = QueueInfo.class),
        @XmlElement(name = "message-filter", type = MessageFilter.class),
        @XmlElement(name = "message", type = MessageInfo.class),
        @XmlElement(name = "topic", type = TopicInfo.class)
    })
    protected List<Object> messageOrQueueOrTopic;

    /**
     * Gets the value of the messageOrQueueOrTopic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageOrQueueOrTopic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageOrQueueOrTopic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueueInfo }
     * {@link MessageFilter }
     * {@link MessageInfo }
     * {@link TopicInfo }
     * 
     * 
     */
    public List<Object> getMessageOrQueueOrTopic() {
        if (messageOrQueueOrTopic == null) {
            messageOrQueueOrTopic = new ArrayList<Object>();
        }
        return this.messageOrQueueOrTopic;
    }
}