//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 04:28:25 PM PDT 
//


package org.jaffa.modules.messaging.services.configdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         jms-config provides information for connecting to JMS Provider
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;&lt;b&gt;jndi-context&lt;/b&gt;: Provides JNDI context for accessing the JMS Provider&lt;/li&gt;&lt;li&gt;&lt;b&gt;connection-factory&lt;/b&gt;: JNDI name for accessing the JMS connection factory&lt;/li&gt;&lt;li&gt;&lt;b&gt;user&lt;/b&gt;: The user for logging into the JMS Provider&lt;/li&gt;&lt;li&gt;&lt;b&gt;password&lt;/b&gt;: The password for logging into the JMS Provider&lt;/li&gt;

 *         &lt;/ul&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for jms-config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jms-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jndi-context" type="{}jndi-context" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="connection-factory" type="{http://www.w3.org/2001/XMLSchema}string" default="ConnectionFactory" />
 *       &lt;attribute name="user" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jms-config", propOrder = {
    "jndiContext"
})
public class JmsConfig {

    @XmlElement(name = "jndi-context")
    protected JndiContext jndiContext;
    @XmlAttribute(name = "connection-factory")
    protected String connectionFactory;
    @XmlAttribute(required = true)
    protected String user;
    @XmlAttribute(required = true)
    protected String password;

    /**
     * Gets the value of the jndiContext property.
     * 
     * @return
     *     possible object is
     *     {@link JndiContext }
     *     
     */
    public JndiContext getJndiContext() {
        return jndiContext;
    }

    /**
     * Sets the value of the jndiContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link JndiContext }
     *     
     */
    public void setJndiContext(JndiContext value) {
        this.jndiContext = value;
    }

    /**
     * Gets the value of the connectionFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionFactory() {
        if (connectionFactory == null) {
            return "ConnectionFactory";
        } else {
            return connectionFactory;
        }
    }

    /**
     * Sets the value of the connectionFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionFactory(String value) {
        this.connectionFactory = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

}
