//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 04:28:25 PM PDT 
//


package org.jaffa.modules.messaging.services.configdomain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="jms-config" type="{}jms-config"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jmsConfig"
})
@XmlRootElement(name = "config")
public class JndiConfig {

    @XmlElement(name = "jms-config", required = true)
    protected JmsConfig jmsConfig;

    /**
     * Gets the value of the jmsConfig property.
     * 
     * @return
     *     possible object is
     *     {@link JmsConfig }
     *     
     */
    public JmsConfig getJmsConfig() {
        return jmsConfig;
    }

    /**
     * Sets the value of the jmsConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link JmsConfig }
     *     
     */
    public void setJmsConfig(JmsConfig value) {
        this.jmsConfig = value;
    }
}