//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 04:28:25 PM PDT 
//


package org.jaffa.modules.messaging.services.configdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 *         param declares a name-value pair, and is used in various elements of this schema
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;&lt;b&gt;name&lt;/b&gt;: the name of the parameter&lt;/li&gt;&lt;li&gt;&lt;b&gt;value&lt;/b&gt;: the value of the parameter. It could be a literal. Or it could be expression, which gets evaluated at runtime. JaffaMessaging utilizes the Bean Scripting Framework (BSF) for evaluating expressions. It sets up a context for BSF with the following elements

 *             &lt;ul&gt;&lt;li&gt;&lt;b&gt;context&lt;/b&gt;: contains the global context&lt;/li&gt;&lt;li&gt;&lt;b&gt;bean&lt;/b&gt;: contains the POJO&lt;/li&gt;

 *             &lt;/ul&gt;

 *           &lt;/li&gt;&lt;li&gt;&lt;b&gt;loggingName&lt;/b&gt;: the name to use, if this element is to be added to the Map Diagnostoc Context (MDC) of Log4J. It can then be used for writing BusinessEventLog records&lt;/li&gt;&lt;li&gt;&lt;b&gt;expression&lt;/b&gt;: a flag to indicate if the value contains a literal, or an expression that should evaluated at runtime&lt;/li&gt;&lt;li&gt;&lt;b&gt;language&lt;/b&gt;: indicates the scripting language used for writing the expression, if any. It should be compatible with BSF. It defaults to beanshell&lt;/li&gt;

 *         &lt;/ul&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for param complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="param">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="expression" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" default="beanshell" />
 *       &lt;attribute name="loggingName" type="{}loggingName" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "param", propOrder = {
    "value"
})
public class Param {

    @XmlValue
    protected String value;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected Boolean expression;
    @XmlAttribute
    protected String language;
    @XmlAttribute
    protected LoggingName loggingName;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExpression() {
        if (expression == null) {
            return false;
        } else {
            return expression;
        }
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExpression(Boolean value) {
        this.expression = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        if (language == null) {
            return "beanshell";
        } else {
            return language;
        }
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the loggingName property.
     * 
     * @return
     *     possible object is
     *     {@link LoggingName }
     *     
     */
    public LoggingName getLoggingName() {
        return loggingName;
    }

    /**
     * Sets the value of the loggingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoggingName }
     *     
     */
    public void setLoggingName(LoggingName value) {
        this.loggingName = value;
    }

}
