//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 04:28:25 PM PDT 
//


package org.jaffa.modules.messaging.services.configdomain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         queueInfo provides additional information for a Queue
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;&lt;b&gt;display-param&lt;/b&gt;: lists the header elements to display when viewing the Messages in this Queue&lt;/li&gt;&lt;li&gt;&lt;b&gt;security&lt;/b&gt;: controls access to viewing and maintaining messages in a queue&lt;/li&gt;&lt;li&gt;&lt;b&gt;name&lt;/b&gt;: the name of this queue&lt;/li&gt;&lt;li&gt;&lt;b&gt;consumerPolicy&lt;/b&gt;: a flag to indicate if multiple consumers are registered to this Queue. Defaults to 'single'&lt;/li&gt;&lt;li&gt;&lt;b&gt;errorQueue&lt;/b&gt;: a flag to indicate if this Queue is an ERROR queue One and only one queue can be so designated&lt;/li&gt;

 *         &lt;/ul&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for queueInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queueInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="display-param" type="{}display-param" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="security" type="{}security" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="consumerPolicy" type="{}consumerPolicy" default="single" />
 *       &lt;attribute name="errorQueue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queueInfo", propOrder = {
    "displayParam",
    "security"
})
public class QueueInfo {

    @XmlElement(name = "display-param")
    protected List<DisplayParam> displayParam;
    protected Security security;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected ConsumerPolicy consumerPolicy;
    @XmlAttribute
    protected Boolean errorQueue;

    /**
     * Gets the value of the displayParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayParam }
     * 
     * 
     */
    public List<DisplayParam> getDisplayParam() {
        if (displayParam == null) {
            displayParam = new ArrayList<DisplayParam>();
        }
        return this.displayParam;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Security }
     *     
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setSecurity(Security value) {
        this.security = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the consumerPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerPolicy }
     *     
     */
    public ConsumerPolicy getConsumerPolicy() {
        if (consumerPolicy == null) {
            return ConsumerPolicy.SINGLE;
        } else {
            return consumerPolicy;
        }
    }

    /**
     * Sets the value of the consumerPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerPolicy }
     *     
     */
    public void setConsumerPolicy(ConsumerPolicy value) {
        this.consumerPolicy = value;
    }

    /**
     * Gets the value of the errorQueue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isErrorQueue() {
        if (errorQueue == null) {
            return false;
        } else {
            return errorQueue;
        }
    }

    /**
     * Sets the value of the errorQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setErrorQueue(Boolean value) {
        this.errorQueue = value;
    }

}
