//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 04:28:25 PM PDT 
//


package org.jaffa.modules.messaging.services.configdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         security controls access to viewing and maintaining messages in a queue
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;&lt;b&gt;browseQueue&lt;/b&gt;: contains the business-function for controlling access to a queue

 *             &lt;ul&gt;&lt;li&gt;&lt;b&gt;attribute absent&lt;/b&gt;: All users have access to the queue&lt;/li&gt;&lt;li&gt;&lt;b&gt;attribute empty&lt;/b&gt;: No user will have access to the queue&lt;/li&gt;

 *             &lt;/ul&gt;

 *           &lt;/li&gt;&lt;li&gt;&lt;b&gt;browseAllMessages&lt;/b&gt;: contains the business-function for controlling access the messages within an accessible queue. All messages are available if the user has access to the business-function, else the user can view its own Messages only

 *             &lt;ul&gt;&lt;li&gt;&lt;b&gt;attribute absent&lt;/b&gt;: All Messages are visible&lt;/li&gt;&lt;li&gt;&lt;b&gt;attribute empty&lt;/b&gt;: A user can view its own Messages only&lt;/li&gt;

 *             &lt;/ul&gt;

 *           &lt;/li&gt;&lt;li&gt;&lt;b&gt;adminMessage&lt;/b&gt;: contains the business-function for controlling access to the delete and resubmit actions on the accessible Messages within an accessible queue

 *             &lt;ul&gt;&lt;li&gt;&lt;b&gt;attribute absent&lt;/b&gt;: All users can Delete and Resubmit&lt;/li&gt;&lt;li&gt;&lt;b&gt;attribute empty&lt;/b&gt;: No user can Delete and Resubmit&lt;/li&gt;

 *             &lt;/ul&gt;

 *           &lt;/li&gt;&lt;li&gt;&lt;b&gt;changePriority&lt;/b&gt;: contains the business-function for controlling access to the changePriority action on the accessible Messages within an accessible queue

 *             &lt;ul&gt;&lt;li&gt;&lt;b&gt;attribute absent&lt;/b&gt;: All users can change Priority&lt;/li&gt;&lt;li&gt;&lt;b&gt;attribute empty&lt;/b&gt;: No user can change Priority&lt;/li&gt;

 *             &lt;/ul&gt;

 *           &lt;/li&gt;

 *         &lt;/ul&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for security complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="security">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="browseQueue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="browseAllMessages" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adminMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="changePriority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "security")
public class Security {

    @XmlAttribute
    protected String browseQueue;
    @XmlAttribute
    protected String browseAllMessages;
    @XmlAttribute
    protected String adminMessage;
    @XmlAttribute
    protected String changePriority;

    /**
     * Gets the value of the browseQueue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrowseQueue() {
        return browseQueue;
    }

    /**
     * Sets the value of the browseQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrowseQueue(String value) {
        this.browseQueue = value;
    }

    /**
     * Gets the value of the browseAllMessages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrowseAllMessages() {
        return browseAllMessages;
    }

    /**
     * Sets the value of the browseAllMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrowseAllMessages(String value) {
        this.browseAllMessages = value;
    }

    /**
     * Gets the value of the adminMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminMessage() {
        return adminMessage;
    }

    /**
     * Sets the value of the adminMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminMessage(String value) {
        this.adminMessage = value;
    }

    /**
     * Gets the value of the changePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangePriority() {
        return changePriority;
    }

    /**
     * Sets the value of the changePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangePriority(String value) {
        this.changePriority = value;
    }

}
