//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.29 at 04:28:25 PM PDT 
//


package org.jaffa.modules.messaging.services.configdomain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         topicInfo provides additional information for a Topic
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;&lt;b&gt;name&lt;/b&gt;: the name of this topic&lt;/li&gt;&lt;li&gt;&lt;b&gt;consumerPolicy&lt;/b&gt;: a flag to indicate if a consumer is subscribed to this Topic. Defaults to 'single'. Select 'none' if this feature is not required&lt;/li&gt;

 *         &lt;/ul&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for topicInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="topicInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="consumerPolicy" type="{}consumerPolicy" default="single" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "topicInfo")
public class TopicInfo {

    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected ConsumerPolicy consumerPolicy;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the consumerPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerPolicy }
     *     
     */
    public ConsumerPolicy getConsumerPolicy() {
        if (consumerPolicy == null) {
            return ConsumerPolicy.SINGLE;
        } else {
            return consumerPolicy;
        }
    }

    /**
     * Sets the value of the consumerPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerPolicy }
     *     
     */
    public void setConsumerPolicy(ConsumerPolicy value) {
        this.consumerPolicy = value;
    }

}
