//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.09 at 01:41:50 PM PST 
//


package org.jaffa.presentation.portlet.component.componentdomain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jaffa.presentation.portlet.component.componentdomain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jaffa.presentation.portlet.component.componentdomain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UseDesignPattern }
     * 
     */
    public UseDesignPattern createUseDesignPattern() {
        return new UseDesignPattern();
    }

    /**
     * Create an instance of {@link ObjectTypeParam }
     * 
     */
    public ObjectTypeParam createObjectTypeParam() {
        return new ObjectTypeParam();
    }

    /**
     * Create an instance of {@link MandatoryFunction }
     * 
     */
    public MandatoryFunction createMandatoryFunction() {
        return new MandatoryFunction();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link IntTypeParam }
     * 
     */
    public IntTypeParam createIntTypeParam() {
        return new IntTypeParam();
    }

    /**
     * Create an instance of {@link DependentComponent }
     * 
     */
    public DependentComponent createDependentComponent() {
        return new DependentComponent();
    }

    /**
     * Create an instance of {@link Component.Params }
     * 
     */
    public Component.Params createComponentParams() {
        return new Component.Params();
    }

    /**
     * Create an instance of {@link StringTypeParam }
     * 
     */
    public StringTypeParam createStringTypeParam() {
        return new StringTypeParam();
    }

    /**
     * Create an instance of {@link UseDesignExtension }
     * 
     */
    public UseDesignExtension createUseDesignExtension() {
        return new UseDesignExtension();
    }

    /**
     * Create an instance of {@link OptionalFunction }
     * 
     */
    public OptionalFunction createOptionalFunction() {
        return new OptionalFunction();
    }

    /**
     * Create an instance of {@link BooleanTypeParam }
     * 
     */
    public BooleanTypeParam createBooleanTypeParam() {
        return new BooleanTypeParam();
    }

}
