SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_AUDIT_TRANSACTION_OBJECTS"(
        "OBJECT_ID"          VARCHAR(80) NOT NULL,
        "TRANSACTION_ID"          VARCHAR(80) NOT NULL,
        "OBJECT_NAME"          VARCHAR(80) NOT NULL,
        "CHANGE_TYPE"          VARCHAR(1),
    CONSTRAINT "J_AUDIT_TRANSACTION_OBJECTSP1" PRIMARY KEY("OBJECT_ID")
)
GO
