SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE "J_AUDIT_TRANSACTIONS"(
        "TRANSACTION_ID"          VARCHAR(80) NOT NULL,
        "PROCESS_NAME"          VARCHAR(80),
        "SUB_PROCESS_NAME"          VARCHAR(80),
        "REASON"          VARCHAR(250),
        "CREATED_BY"          VARCHAR(20),
        "CREATED_ON"          DATETIME,
    CONSTRAINT "J_AUDIT_TRANSACTIONSP1" PRIMARY KEY("TRANSACTION_ID")
)
GO
