//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.12 at 05:13:00 PM PDT 
//


package org.jaffa.soa.services.configdomain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jaffa.soa.services.configdomain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jaffa.soa.services.configdomain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link SoaEvents }
     * 
     */
    public SoaEvents createSoaEvents() {
        return new SoaEvents();
    }

    /**
     * Create an instance of {@link InjectDomainFact }
     * 
     */
    public InjectDomainFact createInjectDomainFact() {
        return new InjectDomainFact();
    }

    /**
     * Create an instance of {@link SoaEventInfo }
     * 
     */
    public SoaEventInfo createSoaEventInfo() {
        return new SoaEventInfo();
    }

}
